version: '3.8'

services:
  nginx:
    image: nginx:1.22.1-alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./app/public:/app/public:rw
    ports:
      - 80:80
    depends_on:
      app:
        condition: service_started
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: local/app
    container_name: app
    volumes:
      - ./app:/app:rw
